### ISSUE TITLE
Add Warren to Org and DevOps Team

### ISSUE THREAD

**Issue by patrick-kep** [woodshedarchive/woodshedarchive.github.io#7]

**Comment by wcrigger** [comment]
Think I'm added....not sure if all the way yet...but I am able to modify settings..some at least.

What help do you require?

Thanks,
Warren

**Comment by patrick-kep** [comment]
I am fine with you being a super admin, but I am playing with settings.  reallly the only goal is to make this thing look cool and make our life easier.  I hope if we just lay all the stuff we do out here we can get some help.  I have been having pretty good luck getting help and having fun helping strangers as long as I everyone is realistic about time and everyone is clear about what we are trying to do.  You and I are not the only cats out there that can't sleep, looking for geeky things to do... he he he...   github is sort of ADD heaven.  Have you seen the project board and the website repo.  I have a couple private repos to clone over to the org over the next couple months.
