### ISSUE TITLE
Use bootleg.woodshedarchive.org for https://github.com/woodshedarchive/woodshedarchive.github.io

### ISSUE THREAD

**Issue by patrick-kep** [woodshedarchive/woodshedarchive.github.io#8]
Custom domains allow you to serve your site from a domain other than woodshedarchive.github.io. [Learn more](https://help.github.com/articles/using-a-custom-domain-with-github-pages)

https://bootleg.woodshedarchive.org
https://github.com/woodshedarchive/woodshedarchive.github.io
https://github.com/woodshedarchive/woodshedarchive.github.io/settings

**Comment by wcrigger** [comment]
Added CNAME, removed NGINX bootleg.conf and bootleg-test.conf (in disabled dir)....and added our custom domain to Github.

Works with text based browsers, but my browser @ the office seems quirky.  Github advised to wait up to an hour for the SSL changes to make their way out.  I also had SNI enabled in nginx, which may be causing an issue.  However, prior to disabling the config, I set it to 0 for a bit.  

It seems now that the cert being presented is valid for *.github.io sites, which ours is hosted on, but our custom domain I suppose isn't included in that (yet?).....

Will follow up later...

**Comment by wcrigger** [comment]
[https://help.github.com/articles/troubleshooting-custom-domains/#https-errors]https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by wcrigger** [comment]
bootleg.woodshedarchive.org uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com Error code: SSL_ERROR_BAD_CERT_DOMAIN


Hoping the resolution to this is....time, per:

t can take up to an hour for your GitHub Pages site to become available over HTTPS after you add and correctly configure your custom domain. After updating existing DNS settings, you may need to remove and re-add your custom domain to your GitHub account to trigger the process of enabling HTTPS. For more information, see "Using a custom domain with GitHub Pages."

...the custom domain was removed + readded...we shall see.

**Comment by patrick-kep** [comment]
I noticed there were some issues, are we a bit ahead of the curve with our configuration?

**Comment by patrick-kep** [comment]
Warren,

So this is not really our issue anymore.  Either they start generating a certificate with the correct domain name or give us the ability to generate a cert for our site with the correct name.  If not we will have to move the site over back to our site.  It is a really simple Jekyll site.  https://jekyllrb.com/  I just thought it would be nice to let them deal with it in the damn "cloud".   I would prefer to build a base container for prod, but this one worked and did not have a bunch of crap installed to play around and get started https://hub.docker.com/r/grahamc/jekyll/

**Comment by wcrigger** [comment]
seems like time solved the issue.  I already had HSTS enabled so browsing via HTTP was denied.  I reset HSTS and removed and readded the custom domain in settings as the FAQ suggested, and sure enough it's working now.   I'm venturing over to the HSTS setting in GitHub now to see if enforcing it is an option....but I got here by trying the http:// URL and it was seamlessly redirected to https://.  😁

**Comment by wcrigger** [comment]
OK, I enabled HSTS via settings for this domain.  Sweet.
